version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/lib/api/template"
    schedule:
      interval: "monthly"
    reviewers: 
      - "Muh-Hasan"
  - package-ecosystem: "npm"
    directory: "/src/lib/api/template/lambdaLayer"
    schedule:
      interval: "monthly"
    reviewers: 
      - "Muh-Hasan"
